# Generated by Django 5.1.3 on 2024-11-25 05:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorterbangApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
