# Generated by Django 5.1.3 on 2024-11-25 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorterbangApp', '0004_alter_barang_jenis_barang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='jenis_barang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorterbangApp.jenis'),
        ),
    ]
