# Generated by Django 5.1.3 on 2024-11-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorterbangApp', '0005_alter_barang_jenis_barang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='jenis_barang',
        ),
    ]
