# Generated by Django 5.1.3 on 2024-11-25 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorterbangApp', '0006_remove_barang_jenis_barang'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='jenis_barang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motorterbangApp.jenis'),
        ),
    ]
