# Generated by Django 5.1.3 on 2024-11-25 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorterbangApp', '0008_komponen_mataanggaran_sumberanggaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='komponen',
            name='mata_anggaran',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motorterbangApp.mataanggaran'),
        ),
        migrations.AddField(
            model_name='komponen',
            name='sumber_anggaran',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motorterbangApp.sumberanggaran'),
        ),
    ]
