# Generated by Django 5.1.3 on 2024-11-26 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorterbangApp', '0009_komponen_mata_anggaran_komponen_sumber_anggaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penyedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penyedia', models.CharField(max_length=100)),
                ('alamat_penyedia', models.CharField(max_length=300)),
                ('pimpinan_penyedia', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mataanggaran',
            name='jumlah_anggaran',
        ),
        migrations.CreateModel(
            name='ReferensiHarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referensi_penyedia', models.CharField(max_length=100)),
                ('harga_referensi', models.PositiveIntegerField(default=0)),
                ('link_referensi', models.CharField(max_length=300)),
                ('data_referensi', models.FileField(upload_to='')),
                ('nama_barang', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motorterbangApp.barang')),
            ],
        ),
    ]
